#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.18f1_bbf64de26e34"
#define UNITY_VERSION_FULL_NICE "2019.2.18f1 (bbf64de26e34)"
#define UNITY_VERSION_BLD 12318285
#define UNITY_VERSION_DATE 1578382325
#define UNITY_VERSION_WIN "2019.2.18.12318285"
#define UNITY_VERSION_BRANCH "2019.2/staging"
